---
- name: Task 1
  hosts: all
  become: true
  vars:
    groups:
      - Sales
      - IT
      - Support
      - Services
  tasks:
    - name: Create Groups
      ansible.builtin.group:
        name: "{{ item }}"
      loop: "{{ groups }}"

    - name: Create Users
      ansible.builtin.user:
        name: "{{ item[0] }}"
        group: "{{ item[1] }}"
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
        - [Annabelle, Sales]
        - [Bob, IT]
        - [Carl, Support]
        - [Dyson, Support]
        - [Evert, IT]
        - [Frank, Sales]
        - [Gerry, Support]
        - [Harold, IT]
        - [Isabella, Services]
        - [Jameson, Services]

    - name: Create folders
      ansible.builtin.file:
        state: directory
        path: "/team/{{ item }}"
        group: "{{ item }}"
        mode: '0077'
      loop: "{{ groups }}"
    
    - name: Create sales file
      ansible.builtin.file:
        path: /sales/Salesnumbers
        mode: '0666'
    
    - name: Add line to file
      ansible.builtin.lineinfile:
        path: /it/tasks.done
        line: 'all folders are set'
        state: present
        create: true
        insertbefore: BOF
        mode: '0666'
