---
- name: Task 1
  hosts: localhost
  tasks:
    - name: Create Groups
      ansible.builtin.group:
        name: item
      loop:
        - Sales
        - IT
        - Support
        - Services

    - name: Create Users
      ansible.builtin.user:
        name: item[0]
        group: item[1]
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
        - [Annabelle, Sales]
        - [Bob, IT]
        - [Carl, Support]
        - [Dyson, Support]
        - [Evert, IT]
        - [Frank, Sales]
        - [Gerry, Support]
        - [Harold, IT]
        - [Isabella, Services]
        - [Jameson, Services]
