- name: Ensure storage exists on rhel
  hosts: server2
  collections:
    - ansible.posix
    - rhel_system_roles
  vars: 
    storage_volumes:
      - name: extdrive
        state: present
        device: /dev/nvme1n1
        fs_type: xfs
        size: 1G
        automount: yes
        mount_point: /extdrive
        group: ITxs
        mode: 0770
  roles: 
    - rhel_system_roles.storage